grafana:
    cloud:
        url: https://dmtrglobal.grafana.net
        auth: ENC[AES256_GCM,data:IoP4qtSZCJvCrdLWnrbpSFCopr7aYL25PYWlRp19+1g31P7cpLdpCb8en1b4qg==,iv:XKiKfS+ESZrHv8Y6nDs6YBIBzKDZal0KV2uZZaWAfio=,tag:FNv7IyoeafukzUZiRuDX/g==,type:str]
        sm_url: https://synthetic-monitoring-api-sa-east-1.grafana.net
        sm_access_token: ENC[AES256_GCM,data:JElNGphWYBLP5f5tT0K1WkUK4XeVdC6A2p3BbmfI9yRVBwqDK4cC1pFNF0DEWgGnzd0nWEFCj+3jjdiM/waTqm6TEij9GNoER7YMIIBKcUYnAAq0go5OGKoN4vE/FP7lGLlmHzJ9GCQgqAb6oMj797Hj2UM=,iv:vLunu9AvZb3AQGiyYliVy6H0wGK4Qo1l4BSojhwTNjA=,tag:6eFJ+/LBzsP0mKlD1ha1+A==,type:str]
        discord_webhook_url: ENC[AES256_GCM,data:PkpmmXqwvP0B9gsTZzR9KShXDKbj5N69NLYbsC0gtdJc5b598ddqDn8DNad0dVXQB3o1Spp0xKAIOOa/uJh2USW3sqHXfw37tct/NSbc/qT+MsbnIrucoHYi6JUW8z1JKVkp45lyihXUo82Wa94JL7LXtxwq41DTqQ==,iv:2nOjUB2hjJNW1oiJ8tJvCqFLVb/fsf3wrpCMEoSYzLc=,tag:D9lNyAQx/C0hcSUAln26ow==,type:str]
    folders:
        - local_directory: grafana/dashboards/blinklabs
          grafana_title: Demeter Blink Labs
          datasource_uids:
            datasource_uid: gke_blinklabs-demeter_us-central1_dmtr-cluster-prometheus
        - local_directory: grafana/dashboards/txpipe
          grafana_title: Demeter TxPipe
          datasource_uids:
            datasource_uid: aws_txpipe-demeter_us-west-2_m2-prometheus
        - local_directory: grafana/dashboards/shared
          grafana_title: Demeter Shared
    data_sources:
        gke_blinklabs-demeter_us-central1_dmtr-cluster-prometheus:
            type: prometheus
            name: gke_blinklabs-demeter_us-central1_dmtr-cluster-prometheus
            url: http://prometheus-operated.dmtr-system.svc.cluster.local:9090
            pdc: 46f68690-716c-47ff-91d0-26359c834aae
        aws_txpipe-demeter_us-west-2_m2-prometheus:
            type: prometheus
            name: aws_txpipe-demeter_us-west-2_m2-prometheus
            url: http://prometheus-operated.demeter-system.svc.cluster.local:9090
            pdc: 46f28c91-2d0f-401b-ac87-5afd0a75f667
    alerts:
        - local_directory: grafana/alerts/blinklabs
          grafana_title: Blink Labs
          folder_uid: fe24y2dswncowc
        - local_directory: grafana/alerts/demeter
          grafana_title: Demeter
          folder_uid: de9p56uby56v4a
    synthetics_checks:
        - job_name: queryNetworkTip
          target: blinklabs-ogmios-cardano-preview
          frequency: 600000
          timeout: 15000
          url: wss://preview.ogmios.blinklabs.cloud
          api_key: ENC[AES256_GCM,data:dgBulpVYVqNE/FSZ2HEUe2mXlfkQYW2Yc0I=,iv:o/xqGGpe4YcmedZtUut7+1SiyN7ZB85LeG0rRW4xnVE=,tag:MTPmwV4dwQFAGXbLlQJs5w==,type:str]
          script_path: grafana/synthetics/shared/ogmiosQueryNetworkTip.js
        - job_name: queryNetworkTip
          target: blinklabs-ogmios-cardano-preprod
          frequency: 600000
          timeout: 15000
          url: wss://preprod.ogmios.blinklabs.cloud
          api_key: ENC[AES256_GCM,data:sui1AfI03kkI77yGWUoxI2j0OdQbkNSHsAY=,iv:lj0yVH2mzhc9XcoR+MlZDKxW4lAtTkn88XMECDWVPpc=,tag:FaxtanGlmHrDnLwa5hpCxA==,type:str]
          script_path: grafana/synthetics/shared/ogmiosQueryNetworkTip.js
        - job_name: queryNetworkTip
          target: blinklabs-ogmios-cardano-mainnet
          frequency: 600000
          timeout: 15000
          url: wss://ogmios.blinklabs.cloud
          api_key: ENC[AES256_GCM,data:o6pDpCCO+kflseHV7MXHoTBBWaRzJaMUGPM=,iv:n+wUtpSX7EbFWMMONVeoq2Fl3e0xgGpfmZV12Oej5vY=,tag:Dy8/Gh5zBsPfSK8LHHG7IQ==,type:str]
          script_path: grafana/synthetics/shared/ogmiosQueryNetworkTip.js
        - job_name: dmtr_healthcheck
          target: blinklabs-kupo-cardano-mainnet
          frequency: 600000
          timeout: 15000
          url: https://demeter.blinklabs.cloud:4442
          api_key: ENC[AES256_GCM,data:S8qsUAtKr74BnX0nl6ldsIe+iqpVfmem,iv:brwUIwVxnsg1NFJlb5YI7kajt7YHKWXBGKSUrYOeLUg=,tag:RXd9dUEk5BjwskoBMibtHQ==,type:str]
          script_path: grafana/synthetics/shared/dmtrHealth.js
        - job_name: dmtr_healthcheck
          target: blinklabs-kupo-cardano-preprod
          frequency: 600000
          timeout: 15000
          url: https://demeter.blinklabs.cloud:4442
          api_key: ENC[AES256_GCM,data:EzAzBlSU04LNsWgVvti9x3EoR3L8MdxQ,iv:z0jZEnj9BnzkbwrHKQvRHsjEPKHA99FIl/nyUsGXthk=,tag:KVAxhNswiMMCbaXSORgglg==,type:str]
          script_path: grafana/synthetics/shared/dmtrHealth.js
        - job_name: dmtr_healthcheck
          target: blinklabs-kupo-cardano-preview
          frequency: 600000
          timeout: 15000
          url: https://demeter.blinklabs.cloud:4442
          api_key: ENC[AES256_GCM,data:zTej24J2N42P5+EY+r6evG+QGCvmNSA2,iv:d64E3gSHe3Y/XnREZjKC5Z/YL58lUiRq3SQZie8Oy8k=,tag:KJs7JjOaiPaa/nDzuywecQ==,type:str]
          script_path: grafana/synthetics/shared/dmtrHealth.js
sops:
    age:
        - recipient: age1klj2c5sj490j2g6ptlf3uh5cwehr4jfdt6c2e638a939sf7pfcdqjm54hq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZ2UwTlk5T2c1bkxSR1Rq
            bGpVbjh2QXV3QlRrWVZiTi8rV0Q3Z1JVUnhnCmY0aHo0b2RLWWR6R0pjbHdnVzQw
            MjdBdjBPaEtYdHp1R3hjd0dnZ1d3VXcKLS0tIElGVG1ESE4zYVJBWG42MVJHQXVY
            UkJmSzN5TElJaHlGTU5BUWJmMDhIa2sKOYr4ZjQfOAngysJNBnhbY7tolAvVQkTt
            Qg2K4CsC5ni3cadqUDJgalpGjgE4t5G30LddsYnSyMF7kXf552ndxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-25T17:18:06Z"
    mac: ENC[AES256_GCM,data:i2tI3aLiQS3/gnVqTHt5hzUHrabQK+CHwmID1Po8/6MPbl7gYEdKYc+rOwvD9/AL74A8GdWAjsAsLM+GUPl3M6Ybx+DcYl5Lfvz689dn5y8HB6QyrTzBtdwwsoM/tgNsW8jqFitG6GlKz1M2SaTbrB9VYK22ABmOVFP12m6WMiw=,iv:X8DxUcXQjQuTtaY510ru9MYcD4fdJZHBg5wd+YB9Dgg=,tag:TShSDQBBWbxK/D9YmEjmBQ==,type:str]
    encrypted_regex: ^(auth|sm_access_token|api_key|discord_webhook_url)$
    version: 3.12.1
