grafana:
    cloud:
        url: https://dmtrglobal.grafana.net
        auth: ENC[AES256_GCM,data:7Wbq1IRDNeIXPA3X8EwMABCZePLKKMClf0OD7W3TxzqwH27m7B5EyqSVE5/8hw==,iv:Hj7Ppns3XYnU4cxEvNW5MvhcHBmYv800j+BPXGeC3t4=,tag:E/MBlYplPHjPUoH0E0bVeQ==,type:str]
    folders:
        - local_directory: grafana/dashboards/demeter
          grafana_title: Demeter Blink Labs
          datasource_uids:
            datasource_uid: gke_blinklabs-demeter_us-central1_dmtr-cluster-prometheus
        - local_directory: grafana/dashboards/demeter
          grafana_title: Demeter TxPipe
          datasource_uids:
            datasource_uid: aws_txpipe-demeter_us-west-2_m2-prometheus
    data_sources:
        gke_blinklabs-demeter_us-central1_dmtr-cluster-prometheus:
            type: prometheus
            name: gke_blinklabs-demeter_us-central1_dmtr-cluster-prometheus
            url: http://prometheus-operated.dmtr-system.svc.cluster.local:9090
            pdc: 46f68690-716c-47ff-91d0-26359c834aae
        aws_txpipe-demeter_us-west-2_m2-prometheus:
            type: prometheus
            name: aws_txpipe-demeter_us-west-2_m2-prometheus
            url: http://prometheus-operated.dmtr-system.svc.cluster.local:9090
            pdc: 46f28c91-2d0f-401b-ac87-5afd0a75f667
    alerts:
        - local_directory: grafana/alerts/blinklabs
          grafana_title: Blink Labs
          folder_uid: fe24y2dswncowc
        - local_directory: grafana/alerts/demeter
          grafana_title: Demeter
          folder_uid: de9p56uby56v4a
sops:
    age:
        - recipient: age1klj2c5sj490j2g6ptlf3uh5cwehr4jfdt6c2e638a939sf7pfcdqjm54hq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNHhFVkh6eGc0QTVUNTZk
            OHgxcllnOHNWODVpUUZMZUlCWng1ZjhZWlhnCmkyZWNxbFlZMEN1YUo0akJWdkdW
            OXNKR1cvQVhEMVJMRk56WXg3YTB2ZlEKLS0tIFQ1bGRrYXErQ2RwOUJSekQwUzAw
            UEtmcVpPQlMzWXNaeS93bndHTmdMYWMKr5pcKioeQQJ2QH43yhfRb2T/mTRCDnfg
            SDF1sbPenrnDJRA8Gi9CphX9bPz3XtkjRTsFYxD/hW1doSTiflkVJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-09T16:36:24Z"
    mac: ENC[AES256_GCM,data:qt6HTWggIRboeMVKl5GSbdrzxzQvLPXr74RV9NXRCJAu4OSMmHH4+G/AINSys+YaqbTrwYg9k8L7+Oryn824+Df4OKsZfZk8DRSwi0dZBfLdNcQ8Koh+5UtWKYuboYfKPgIBj5CUn59eya9MnUv0ryrFWgS5vRJPf4h/oTTsBk0=,iv:c/SwlhSzxCQNfnAa08wl7j28OS+ECNIbDSZsqoMStRo=,tag:h5EVkA9QUbRQURhvQurqcA==,type:str]
    encrypted_regex: ^(auth)$
    version: 3.11.0
