grafana:
    cloud:
        url: https://dmtrglobal.grafana.net
        auth: ENC[AES256_GCM,data:WiaDXoAvGJqDHU2FF1rFjAhAB1V9p7EqYdmZn4VcCk0WXs1YD7ba1LiaSlgIHA==,iv:Yd8LknkpFEOilkaMbZZ6SRO9YyU8w3oLrnOWvkJh1Vk=,tag:s97efgv37A3TTylfHqi68w==,type:str]
        sm_url: https://synthetic-monitoring-api-sa-east-1.grafana.net
        sm_access_token: ENC[AES256_GCM,data:My3nmcwgd/j560EoxU+/6ugFeI4JAlE5f/PN+b23wfXGq9EL1zP7vYRi90ahTm5GtkVhWAsTQvYHIjIO4DUfKtD9Fi7Uq1ZobeTKhLUWqpQ66J3BBFe4j5ZBSZt25gbGBeUGJ5KYDdYd2sQmukUx0UEBpXQ=,iv:v8QW0N+gSevAUbIcHAj5d4CQcvVQZVJyWXfbOZ0LA1U=,tag:DMVZPhGdI/NAmDWhbaN4Ug==,type:str]
    folders:
        - local_directory: grafana/dashboards/blinklabs
          grafana_title: Demeter Blink Labs
          datasource_uids:
            datasource_uid: gke_blinklabs-demeter_us-central1_dmtr-cluster-prometheus
        - local_directory: grafana/dashboards/txpipe
          grafana_title: Demeter TxPipe
          datasource_uids:
            datasource_uid: aws_txpipe-demeter_us-west-2_m2-prometheus
        - local_directory: grafana/dashboards/shared
          grafana_title: Demeter Shared
    data_sources:
        gke_blinklabs-demeter_us-central1_dmtr-cluster-prometheus:
            type: prometheus
            name: gke_blinklabs-demeter_us-central1_dmtr-cluster-prometheus
            url: http://prometheus-operated.dmtr-system.svc.cluster.local:9090
            pdc: 46f68690-716c-47ff-91d0-26359c834aae
        aws_txpipe-demeter_us-west-2_m2-prometheus:
            type: prometheus
            name: aws_txpipe-demeter_us-west-2_m2-prometheus
            url: http://prometheus-operated.demeter-system.svc.cluster.local:9090
            pdc: 46f28c91-2d0f-401b-ac87-5afd0a75f667
    alerts:
        - local_directory: grafana/alerts/blinklabs
          grafana_title: Blink Labs
          folder_uid: fe24y2dswncowc
        - local_directory: grafana/alerts/demeter
          grafana_title: Demeter
          folder_uid: de9p56uby56v4a
    synthetics_checks:
        - job_name: queryNetworkTip
          target: blinklabs-ogmios-cardano-preview
          frequency: 600000
          timeout: 15000
          url: wss://preview.ogmios.blinklabs.cloud
          api_key: ENC[AES256_GCM,data:GblmmgBMVTJor7EtefD8yPTeMTa5noBka+8=,iv:oC2B+8AJWjhD5QmQGIaVtFGhFRo7inPJICzSAB57HmM=,tag:9EnJ0UMohqTQMw1hxHjeXQ==,type:str]
          script_path: grafana/synthetics/shared/ogmiosQueryNetworkTip.js
        - job_name: queryNetworkTip
          target: blinklabs-ogmios-cardano-preprod
          frequency: 600000
          timeout: 15000
          url: wss://preprod.ogmios.blinklabs.cloud
          api_key: ENC[AES256_GCM,data:yqcaOAitNcpZQi4YuxlR7OI6NHHLLGk2EgM=,iv:J6JUaSq8gbRmyXXg+Dcn51PdOsY8dR4fcX9Rtkysl6A=,tag:mxII7XmAxweQn+AHhiMaZg==,type:str]
          script_path: grafana/synthetics/shared/ogmiosQueryNetworkTip.js
        - job_name: queryNetworkTip
          target: blinklabs-ogmios-cardano-mainnet
          frequency: 600000
          timeout: 15000
          url: wss://ogmios.blinklabs.cloud
          api_key: ENC[AES256_GCM,data:qIYMsjaAK+HaqmEl+F4lYQdli1rhYvQjYeo=,iv:zvxWA1GKueOGnAxDcer6DSY5C8emqCrdm0rK7ZVtV8U=,tag:bfA8H5TRAmdxnmpcVW+9rg==,type:str]
          script_path: grafana/synthetics/shared/ogmiosQueryNetworkTip.js
        - job_name: dmtr_healthcheck
          target: blinklabs-kupo-cardano-mainnet
          frequency: 600000
          timeout: 15000
          url: https://kupo.blinklabs.cloud
          api_key: ENC[AES256_GCM,data:rreo02BkR9gA+7PJLtyVgch0Herj8CV7,iv:FzGoRRhomHbPsmRGEF98BR2G5yYQpUkUMLpqNQw2W5w=,tag:vpg0a/lRy0PETWS9PFHsuQ==,type:str]
          script_path: grafana/synthetics/shared/dmtrHealth.js
        - job_name: dmtr_healthcheck
          target: blinklabs-kupo-cardano-preprod
          frequency: 600000
          timeout: 15000
          url: https://preprod.kupo.blinklabs.cloud
          api_key: ENC[AES256_GCM,data:KSHihtAGMBXeNVhthDYHOlvvTD92M1Zi,iv:/FmhD2Y7agR3xA5Q7vm6m9kV35oLmfjEJWa+FvMuuAo=,tag:iEtaapaFrBCLcOuQXTztZg==,type:str]
          script_path: grafana/synthetics/shared/dmtrHealth.js
        - job_name: dmtr_healthcheck
          target: blinklabs-kupo-cardano-preview
          frequency: 600000
          timeout: 15000
          url: https://preview.kupo.blinklabs.cloud
          api_key: ENC[AES256_GCM,data:cl62glHs+z4MXHkeekkNBTgA3o4Phgdt,iv:lTxRgO+BtiQB2pSY3s4zmu0jWFE88SK+ycdvwNMUuEc=,tag:1YZgjLtFkv+To14CYfZrTg==,type:str]
          script_path: grafana/synthetics/shared/dmtrHealth.js
sops:
    age:
        - recipient: age1klj2c5sj490j2g6ptlf3uh5cwehr4jfdt6c2e638a939sf7pfcdqjm54hq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySW5KTUtjb1dCcklwdFFq
            ZUtiSkpqNHJGQnYvdTd1TE1rM0tOc3pzM2tnClMwaUtqTmN5QkhRcDhRQ1Blc0Zp
            ZExYLzlQNGNTNXZ0L3ZoT0xTSjZqUUUKLS0tIDhSQkZndCtxU0xDRGVBcjRtc3RJ
            UkFLdFMzL1ZPejBWZ1FTR0p0ZlAxVzAKFrgiiE31lMtPT4JSpzD0USBaCT/O4VcZ
            1XZD2KAEDwhq/43Sf9qBCKKjFG0KwKkcrvGqfdtp1M6OPkvPCcOoDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T02:06:48Z"
    mac: ENC[AES256_GCM,data:doRtY9wllYDRBI0qqD0bP1spVjoQ9alqAAsHSJR2yz8Fg7O8EGYKKVudBeY3AE2jt0ifR4dGv1m6d54yyzzADq9KI4xr5aboK05i6Jlz8B7dq+RSBY4xe/5fWamuX1DHn0uyDPls6lnGI+2VfSd+zXTfCxMflOTe/fW8JdEGsPo=,iv:c4s4NhsymVwRwldWN6XHJPh2YUOW61Ty5P8f3oOMGWI=,tag:611RnDKOjfYJnvhO8wbdkA==,type:str]
    encrypted_regex: ^(auth|sm_access_token|api_key)$
    version: 3.10.2
