grafana:
    cloud:
        url: https://dmtrglobal.grafana.net
        auth: ENC[AES256_GCM,data:zvi8gW0/hkqy0n4O/2qv8kAktRtwlDKPCAnveLYiCexTUb3T7O/ZMHEX77b+GQ==,iv:3lsht3gjPTOb8B8nCPC4tpQLI9Ugedc9ALPTaocGGUs=,tag:tBEwlDAhSin21od7vr1DIQ==,type:str]
        sm_url: https://synthetic-monitoring-api-sa-east-1.grafana.net
        sm_access_token: ENC[AES256_GCM,data:Pq+XEkhIgBbZEdwaQOuQ0A7/prj6T1fX5qnbmgFvIIwnuFFw59Kfj/YzuYtN5E88TopiK8i1uvYZF1bXBfsqqKaArZTIXPkbaUZ8WwW20M2AIxEUWrgIKOibq6bAIaeXEaNfPRTRcbLwnjuzqx/eF811H8I=,iv:G4hU1Z6zgtiN/Y47IV9jXUBsHyv2LTucC+RwwEb81/U=,tag:H4PnMx3jiIchE2RMObS81Q==,type:str]
    folders:
        - local_directory: grafana/dashboards/blinklabs
          grafana_title: Demeter Blink Labs
          datasource_uids:
            datasource_uid: gke_blinklabs-demeter_us-central1_dmtr-cluster-prometheus
        - local_directory: grafana/dashboards/txpipe
          grafana_title: Demeter TxPipe
          datasource_uids:
            datasource_uid: aws_txpipe-demeter_us-west-2_m2-prometheus
        - local_directory: grafana/dashboards/shared
          grafana_title: Demeter Shared
    data_sources:
        gke_blinklabs-demeter_us-central1_dmtr-cluster-prometheus:
            type: prometheus
            name: gke_blinklabs-demeter_us-central1_dmtr-cluster-prometheus
            url: http://prometheus-operated.dmtr-system.svc.cluster.local:9090
            pdc: 46f68690-716c-47ff-91d0-26359c834aae
        aws_txpipe-demeter_us-west-2_m2-prometheus:
            type: prometheus
            name: aws_txpipe-demeter_us-west-2_m2-prometheus
            url: http://prometheus-operated.demeter-system.svc.cluster.local:9090
            pdc: 46f28c91-2d0f-401b-ac87-5afd0a75f667
    alerts:
        - local_directory: grafana/alerts/blinklabs
          grafana_title: Blink Labs
          folder_uid: fe24y2dswncowc
        - local_directory: grafana/alerts/demeter
          grafana_title: Demeter
          folder_uid: de9p56uby56v4a
    synthetics_checks:
        - job_name: queryNetworkTip
          target: blinklabs-ogmios-cardano-preview
          frequency: 60000
          timeout: 15000
          url: wss://preview.ogmios.blinklabs.cloud
          api_key: ENC[AES256_GCM,data:aitikjIp9D+LLX5tUiAAiOqlRrdByezSZfo=,iv:fsIoL8waIjG4iPxQDpcAaeowvyXOKfwwlead7HIrXDU=,tag:YUZax6r0tGnaThX6Xb51EQ==,type:str]
          script_path: grafana/synthetics/shared/ogmiosQueryNetworkTip.js
        - job_name: queryNetworkTip
          target: blinklabs-ogmios-cardano-preprod
          frequency: 60000
          timeout: 15000
          url: wss://preprod.ogmios.blinklabs.cloud
          api_key: ENC[AES256_GCM,data:GBdeESLgBHZ2IgGmpRSqsWRSY8flaKFVN4c=,iv:yysPZa7Ph6N+KRBMedJYyJDE7ZxJhxQGtFFUo/T52Fw=,tag:JdsebJ9hZ6NGXBBy36E3qw==,type:str]
          script_path: grafana/synthetics/shared/ogmiosQueryNetworkTip.js
        - job_name: queryNetworkTip
          target: blinklabs-ogmios-cardano-mainnet
          frequency: 60000
          timeout: 15000
          url: wss://ogmios.blinklabs.cloud
          api_key: ENC[AES256_GCM,data:EbkukHR4/jdsgMcuw5Azd+I2TihN9rpYs0M=,iv:WLgb+M4L+BKRgeh9T5Rv1L0WK0BBrltT6rfpWAnOZNs=,tag:zXX0lAtnO1I6UBaEpiWtEw==,type:str]
          script_path: grafana/synthetics/shared/ogmiosQueryNetworkTip.js
sops:
    age:
        - recipient: age1klj2c5sj490j2g6ptlf3uh5cwehr4jfdt6c2e638a939sf7pfcdqjm54hq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUC81QjdlaUFmbzhSUHlr
            RUtBUlExTEVLM05waVlIUEVjaUV2cEdwczFnCnhGaytiblFDYW54dzZ4bkQ0MzJh
            OHFjVm5TSFY4MEZqanlkQ2JiVGZXYzQKLS0tIFI3ZHFHREZvUW8wKzNsSlVTVG96
            NFpHRGZKZVl4U2x4Q2xQRXJNOHpEbUkKAQCBNGTrZT+diaHzxnj38mFTLUi2A0gl
            1v5L/F5uGxRjlLgWdbE/fm5Nycn3eEeRXgatTLApQmGnG5eSFckfbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-01T21:32:40Z"
    mac: ENC[AES256_GCM,data:2til17PBhfAyahzLbFVcahAdkBh2bnXhiZTbM1P2G8MIcR/b/mhcKfgaA4ZwKsHp55N0AcHaNRNHqWtzGrBp/W8uyqZzHHfFFljW0BLbaY1BcMrfGcbnBO+hqhYOHEH35BmLVWWjua+bggfCkn7p3pJCns9EOjGvJvJpThBZz1I=,iv:IOuoL/g5v5mVFtGJ3HpyFGNQ9r2fvDW8Eau5t/iu0t0=,tag:X4qPCvBiFIra6uthcJd1OA==,type:str]
    encrypted_regex: ^(auth|sm_access_token|api_key)$
    version: 3.10.2
