{
 "title": "Cardano Kupo",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "network", "query": "mainnet,preprod,preview" },
   {
    "name": "pod",
    "query": {
     "query": "query_result(kupo_connection_status{pod=~\".*$network.*\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "Instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Slot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "kupo_most_recent_checkpoint{pod=~\".*$pod.*\"}",
     "legendFormat": "{{pod}}.checkpoint"
    },
    {
     "expr": "kupo_most_recent_node_tip{pod=~\".*$pod.*\"}",
     "legendFormat": "{{pod}}.tip"
    }
   ]
  },
  {
   "title": "Sync Delta",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kupo_most_recent_node_tip{pod=~\".*$pod.*\"} - kupo_most_recent_checkpoint{pod=~\".*$pod.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"ftr-kupo-.*\", container=\"main\", pod=~\"$pod\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=~\"ftr-kupo-.*\", container=\"main\", pod=~\"$pod\"}) by (pod) / sum(kube_pod_container_resource_limits{namespace=~\"ftr-kupo-.*\", resource=\"memory\", container=\"main\", pod=~\"$pod\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Space Available",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes{exported_namespace=\"ftr-kupo-v1\"} / on(persistentvolumeclaim) kubelet_volume_stats_capacity_bytes{exported_namespace=\"ftr-kupo-v1\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 17 },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=~\"ftr-kupo-.*\",container=\"main\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Proxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Request Rate by Consumer (blue)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by (consumer)(rate(kupo_proxy_http_total_request{namespace=~\"ftr-kupo-.*\", exported_instance=~\".*$network.*\", job=\"ftr-kupo-v1/proxy\"}[5m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate by Code (blue)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(kupo_proxy_http_total_request{namespace=~\"ftr-kupo-.*\", exported_instance=~\".*$network.*\", job=\"ftr-kupo-v1/proxy\" }[5m]) > 0) by (status_code)",
     "legendFormat": "{{status_code}}.{{consumer}}"
    }
   ]
  },
  {
   "title": "Request Rate by Consumer (green)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by (consumer)(rate(kupo_proxy_http_total_request{namespace=~\"ftr-kupo-.*\", exported_instance=~\".*$network.*\", job=\"ftr-kupo-v1/proxy-green\"}[5m]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate by Code (green)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate(kupo_proxy_http_total_request{namespace=~\"ftr-kupo-.*\", exported_instance=~\".*$network.*\", job=\"ftr-kupo-v1/proxy-green\" }[5m]) > 0) by (status_code)",
     "legendFormat": "{{status_code}}.{{consumer}}"
    }
   ]
  }
 ]
}