{
 "title": "Cardano Node",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "namespace", "query": "ftr-nodes-v2,ext-nodes-m1" },
   {
    "name": "network",
    "query": "mainnet,preview,preprod,sanchonet,vector-testnet,prime-testnet"
   }
  ]
 },
 "panels": [
  {
   "title": "Slot",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotNum_int{namespace=\"$namespace\", pod=~\"(cardano-)?node-$network-.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Block Diff Between Replicas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(cardano_node_metrics_blockNum_int{namespace=\"$namespace\", pod=~\"(cardano-)?node-$network-.*\"})-min(cardano_node_metrics_blockNum_int{namespace=\"$namespace\", pod=~\"(cardano-)?node-$network-.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockNum_int{namespace=\"$namespace\", pod=~\"(cardano-)?node-$network-.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Blocks / Min",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_blockNum_int{namespace=\"$namespace\", pod=~\"(cardano-)?node-$network-.*\"}[5m])*60",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Block Fetch Delay",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_blockfetchclient_blockdelay_s{namespace=\"$namespace\", pod=~\"(cardano-)?node-$network-.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Forks / hour",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(cardano_node_metrics_forks_int{namespace=\"$namespace\", pod=~\"(cardano-)?node-$network-.*\"}[1h])*60*60",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Chain Density",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_density_real{namespace=\"$namespace\", pod=~\"(cardano-)?node-$network-.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Node Disk Space Available",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes{persistentvolumeclaim=~\"data-node-$${network}.*\",exported_namespace=\"$namespace\"} / on(persistentvolumeclaim) kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"data-node-$${network}.*\",exported_namespace=\"$namespace\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 5, "x": 3, "y": 11 },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"$namespace\",container=\"main\", pod=~\"(cardano-)?node-$network-.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Bytes in Mempool",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "cardano_node_metrics_mempoolBytes_int{namespace=\"$namespace\", pod=~\"(cardano-)?node-$network-.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Txs in Mempool",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsInMempool_int{namespace=\"$namespace\", pod=~\"(cardano-)?node-$network-.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage (% or requested quota)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"\", pod=~\"(cardano-)?node-$network-.*\"}[5m])*10000) by (pod) / sum(container_spec_cpu_shares) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (% of quota)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", pod=~\"(cardano-)?node-$network-.*\"}) by (pod) / sum(container_spec_memory_limit_bytes{namespace=\"$namespace\", container!=\"\", pod=~\"(cardano-)?node-$network-.*\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod)(cardano_node_metrics_connectionManager_incomingConns{namespace=\"$namespace\", pod=~\"(cardano-)?node-$network-.*\"})",
     "legendFormat": "incoming.{{pod}}"
    },
    {
     "expr": "sum by (pod)(cardano_node_metrics_connectionManager_duplexConns{namespace=\"$namespace\", pod=~\"(cardano-)?node-$network-.*\"})",
     "legendFormat": "duplex.{{pod}}"
    },
    {
     "expr": "sum by (pod)(cardano_node_metrics_connectionManager_outgoingConns{namespace=\"$namespace\", pod=~\"(cardano-)?node-$network-.*\"})",
     "legendFormat": "outgoing.{{pod}}"
    },
    {
     "expr": "sum by (pod)(cardano_node_metrics_connectionManager_unidirectionalConns{namespace=\"$namespace\", pod=~\"(cardano-)?node-$network-.*\"})",
     "legendFormat": "uni.{{pod}}"
    },
    {
     "expr": "sum by (pod)(cardano_node_metrics_connectionManager_prunableConns{namespace=\"$namespace\", pod=~\"(cardano-)?node-$network-.*\"})",
     "legendFormat": "prunable.{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage (Cores)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"\", pod=~\"(cardano-)?node-$network-.*\"}[1m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy connections by consumer",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum by (consumer) (node_proxy_total_connections{consumer=~\".*$network.*\", exported_instance=~\".*$namespace.*\"}) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections by proxy",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum by (pod) (node_proxy_total_connections{consumer=~\".*$network.*\", exported_instance=~\".*$namespace.*\"}) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy bytes consumed by consumer",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum by (consumer) (rate(node_proxy_total_packages_bytes{consumer=~\".*$network.*\", exported_instance=~\".*$namespace.*\"}[10m])) > 0 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections Denied By Consumer",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "sum by (consumer) (increase(node_proxy_total_connections_denied{consumer=~\".*$network.*\", exported_instance=~\".*$namespace.*\"}[10m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}