{
 "title": "Cardano Ogmios",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "query": "ext-ogmios-m1,ftr-ogmios-v0" },
   { "name": "network", "query": "mainnet,preview,preprod" },
   { "name": "version", "query": "5,6" }
  ]
 },
 "panels": [
  { "title": "Instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ogmios_tip_block{namespace=\"$namespace\", pod=~\".*$network-$version.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Messages / sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "rate(ogmios_total_messages{namespace=\"$namespace\", pod=~\".*$network-$version.*\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ogmios_active_connections{namespace=\"$namespace\", pod=~\".*$network-$version.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 7, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ogmios_active_connections{namespace=\"$namespace\", pod=~\".*$network-$version.*\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Heap Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "ogmios_current_heap_size{namespace=\"$namespace\", pod=~\".*$network-$version.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Ogmios Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"main\", pod=~\".*$network-$version.*\"}[4m])*1000) by (pod) / sum(container_spec_cpu_shares{namespace=\"$namespace\", container=\"main\", pod=~\".*$network-$version.*\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (% of quota)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"socat\", pod=~\".*$network-$version.*\"}) by (pod) / sum(container_spec_memory_limit_bytes{namespace=\"$namespace\", container!=\"socat\", pod=~\".*$network-$version.*\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Health over Time",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "ogmios_connected{namespace=\"$namespace\", pod=~\".*$network-$version.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "ogmios_active_connections{namespace=\"$namespace\", pod=~\".*$network-$version.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Proxy Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"\", pod=~\".*proxy.*\"}[4m])*1000) by (pod) / sum(container_spec_cpu_shares{namespace=\"$namespace\", container!=\"\", pod=~\".*proxy.*\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy Memory Usage (% of quota)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", pod=~\".*proxy.*\"}) by (pod) / sum(container_spec_memory_limit_bytes{namespace=\"$namespace\", container!=\"\", pod=~\".*proxy.*\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Proxy Blue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Frames Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum by (consumer) (rate(ogmios_proxy_ws_total_frame{ exported_instance=~\"ogmios-$${network}.*\", job=\"ext-ogmios-m1/proxy\"}[5m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy Active Connections (Blue)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum by (consumer) (ogmios_proxy_total_connections{exported_instance=~\"ogmios-$${network}.*\", job=\"ext-ogmios-m1/proxy\"}) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request count by Code (blue)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "sum(rate(ogmios_proxy_http_total_request{namespace=~\"ext-ogmios-m1\", exported_instance=~\".*$network.*\",job=\"ext-ogmios-m1/proxy\" }[5m]) > 0) by (status_code, consumer)",
     "legendFormat": "{{status_code}}.{{consumer}}"
    }
   ]
  },
  { "title": "Proxy Green", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Proxy Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "sum by (consumer) (ogmios_proxy_total_connections{exported_instance=~\"ogmios-$${network}.*\", job=~\"ext-ogmios-m1/proxy.*\"}) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request count by Code (green)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "sum(increase(ogmios_proxy_http_total_request{namespace=~\"ext-ogmios-m1\", exported_instance=~\".*$network.*\",job=\"ext-ogmios-m1/proxy-green\" }[5m]) > 0) by (status_code, consumer)",
     "legendFormat": "{{status_code}}.{{consumer}}"
    }
   ]
  },
  {
   "title": "Frames Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "sum by (consumer) (rate(ogmios_proxy_ws_total_frame{ exported_instance=~\"ogmios-$${network}.*\", job=\"ext-ogmios-m1/proxy-green\"}[5m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}