{
 "title": "Blockfrost",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "query": "ext-blockfrost-m1" },
   {
    "name": "network",
    "query": {
     "query": "blockfrost_proxy_http_total_request"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cache hit rate (Blockfrost)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(blockfrost_proxy_http_cache_hits{network=~\".*$network\",resolved_by=\"blockfrost\"}[5m])) / (sum(rate(blockfrost_proxy_http_cache_hits{network=~\".*$network\",resolved_by=\"blockfrost\"}[5m])) + sum(rate(blockfrost_proxy_http_cache_miss{network=~\".*$network\",resolved_by=\"blockfrost\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (exported_instance) (rate(blockfrost_proxy_http_total_request{network=~\".*$network\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (Blockfrost)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(blockfrost_proxy_http_request_duration_seconds_bucket{network=~\".*$network\", proxied=\"true\", resolved_by=\"blockfrost\"}[10m])))",
     "legendFormat": "99"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(blockfrost_proxy_http_request_duration_seconds_bucket{network=~\".*$network\", proxied=\"true\", resolved_by=\"blockfrost\"}[10m])))",
     "legendFormat": "90"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(blockfrost_proxy_http_request_duration_seconds_bucket{network=~\".*$network\", proxied=\"true\", resolved_by=\"blockfrost\"}[10m])))",
     "legendFormat": "50"
    },
    {
     "expr": "histogram_quantile(1, sum by (le) (rate(blockfrost_proxy_http_request_duration_seconds_bucket{network=~\".*$network\", proxied=\"true\", resolved_by=\"blockfrost\"}[10m])))",
     "legendFormat": "p100"
    }
   ]
  },
  {
   "title": "Latency (Dolos)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(blockfrost_proxy_http_request_duration_seconds_bucket{network=~\".*$network\", resolved_by=\"dolos\"}[10m])))",
     "legendFormat": "99"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(blockfrost_proxy_http_request_duration_seconds_bucket{network=~\".*$network\", resolved_by=\"dolos\"}[10m])))",
     "legendFormat": "90"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(blockfrost_proxy_http_request_duration_seconds_bucket{network=~\".*$network\", resolved_by=\"dolos\"}[10m])))",
     "legendFormat": "50"
    }
   ]
  },
  {
   "title": "Cache hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (exported_endpoint) (rate(blockfrost_proxy_http_cache_hits{network=~\".*$network\"}[1m]))",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Cache miss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (exported_endpoint) (rate(blockfrost_proxy_http_cache_miss{network=~\".*$network\"}[5m]))",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Requests rate per code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (status_code) (rate(blockfrost_proxy_http_total_request{network=~\".*$network\"}[1m]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Requests per consumer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by (consumer) (rate(blockfrost_proxy_http_total_request{network=~\".*$network\"}[1m]))",
     "legendFormat": "{{consumer}}"
    }
   ]
  },
  {
   "title": "Dolos Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"ftr-dolos-m1\", container!=\"\", pod=~\"cardano-$network-.*\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Proxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Proxy CPU Usage (milicores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=\"main\", pod=~\"proxy-.*\"}[5m])*1000) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Proxy Memory Usage (% of quota)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", pod=~\"proxy-.*\"}) by (pod) / sum(container_spec_memory_limit_bytes{namespace=\"$namespace\", container!=\"\", pod=~\"proxy-.*\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "CPU Usage (% or requested quota)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container!=\"\", pod=~\".*$network.*\"}[5m])*10000) by (pod) / sum(container_spec_cpu_shares) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage (% of quota)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", container!=\"\", pod=~\".*$network-.*\"}) by (pod) / sum(container_spec_memory_limit_bytes{namespace=\"$namespace\", container!=\"\", pod=~\".*$network-.*\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}