{
 "title": "Cardano DBSync v3",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "network",
    "query": "preview,preprod,mainnet,vector-testnet,prime-testnet"
   }
  ]
 },
 "panels": [
  { "title": "Dbsync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DBSync Disk Space Available",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes{persistentvolumeclaim=~\"state-$network-.*\", exported_namespace=\"ftr-dbsync-v3\" } / on(persistentvolumeclaim) kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"state-$network-.*\", exported_namespace=\"ftr-dbsync-v3\"}",
     "legendFormat": "{{persistenvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Available disk",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_available_bytes{exported_namespace=\"ftr-dbsync-v3\",persistentvolumeclaim=~\"postgres-local-pv-90126e93|pvc.*\"}) / sum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{exported_namespace=\"ftr-dbsync-v3\",persistentvolumeclaim=~\"postgres-local-pv-90126e93|pvc.*\"})"
    }
   ]
  },
  {
   "title": "Sync %",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_db_sync_db_block_height{job=~\"ftr-dbsync-v3/dbsync-$network-.*\"} / cardano_db_sync_node_block_height{job=~\"ftr-dbsync-v3/dbsync-$network-.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Sync Delta",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "blocks" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_db_sync_node_block_height{job=~\"ftr-dbsync-v3/dbsync-$network-.*\"}-cardano_db_sync_db_block_height{job=~\"ftr-dbsync-v3/dbsync-$network-.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Queue Length",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_db_sync_db_queue_length{job=~\"ftr-dbsync-v3/dbsync-$network-.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "DBSync Pod Memory Usage (2b)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(pod)(container_memory_working_set_bytes{namespace=\"ftr-dbsync-v3\",pod=~\"$network-.*\",container!=\"\"})/ sum by (pod)(container_spec_memory_limit_bytes{namespace=\"ftr-dbsync-v3\",pod=~\"$network-.*\",container!=\"\"})\n",
     "legendFormat": "{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Height Increate Rate / minute (2b)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 6 },
   "targets": [
    {
     "expr": "rate(cardano_db_sync_db_block_height{job=~\"ftr-dbsync-v3/dbsync-$network-.*\"}[5m])*60",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "DBSync CPU (2b)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod)(rate(container_cpu_usage_seconds_total{namespace=\"ftr-dbsync-v3\",pod=~\"$network-.*\",container!=\"\"}[$__rate_interval])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Node Block Height (2b)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 13 },
   "targets": [
    {
     "expr": "cardano_db_sync_db_block_height{job=~\"ftr-dbsync-v3/dbsync-$network-.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Postgres", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Postgres Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (pod)(container_memory_working_set_bytes{namespace=\"ftr-dbsync-v3\",pod=~\"postgres-dbsync-v3-.*-0\", container=\"main\"}) / sum by (pod)(container_spec_memory_limit_bytes{namespace=\"ftr-dbsync-v3\",pod=~\"postgres-dbsync-v3-.*-0\", container=\"main\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Postgres CPU (oy0)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod)(rate(container_cpu_usage_seconds_total{namespace=\"ftr-dbsync-v3\",pod=~\"postgres-dbsync-v3-.*-0\", container=\"main\"}[$__rate_interval])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{service=~\"dbsync.*\", datname=~\"dbsync-$network\", job=~\"ftr-dbsync-v3/postgres-.*\"}[$__rate_interval])",
     "legendFormat": "{{service}}-{{datname}} commits"
    }
   ]
  },
  {
   "title": "Transactions distribution per replica",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{service=~\"dbsync.*\", datname=~\"dbsync-$network\", job=~\"ftr-dbsync-v3/postgres-.*\"}[$__range])",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Active sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (usename, datname, service)(pg_stat_activity_count{datname=~\"dbsync-$network\", state=\"active\", job=~\"ftr-dbsync-v3/postgres-.*\"} !=0)",
     "legendFormat": "{{service}}, u: {{usename}}"
    }
   ]
  },
  {
   "title": "Idle sessions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (datname, state, usename, service) (pg_stat_activity_count{datname=~\"dbsync-$network\", state=~\"idle|idle in transaction|idle in transaction (aborted)\", job=~\"ftr-dbsync-v3/postgres-.*\"} !=0)",
     "legendFormat": "{{service}}, s: {{state}}, u: {{usename}}"
    }
   ]
  },
  {
   "title": "Lock tables",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (service, mode, datname)(pg_locks_count{datname=~\"dbsync-$network\", job=~\"ftr-dbsync-v3/postgres-.*\"} != 0)",
     "legendFormat": "{{service}},{{mode}}"
    }
   ]
  },
  {
   "title": "Total sessions per user",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (datname, usename) (pg_stat_activity_count{datname=~\"dbsync-$network\", job=~\"ftr-dbsync-v3/postgres-.*\"} !=0)",
     "legendFormat": "{{service}}, s: {{state}}, u: {{usename}}"
    }
   ]
  },
  {
   "title": "Total Sessions per Instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (datname, service) (pg_stat_activity_count{datname=~\"dbsync-$network\", job=~\"ftr-dbsync-v3/postgres-.*\"} !=0)",
     "legendFormat": "{{service}}, s: {{state}}, u: {{usename}}"
    }
   ]
  }
 ]
}