{
 "title": "UTxO RPC",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "network", "query": "mainnet,preview,preprod" }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(pod, container)(container_memory_working_set_bytes{namespace=~\"dolos|ext-utxorpc-m1\", pod=~\"dolos-$network-az.*|cardano-$network-.*\", container!=\"\"}) / sum by (pod, container)(container_spec_memory_limit_bytes{namespace=~\"dolos|ext-utxorpc-m1\",pod=~\"dolos-$network-az.*|cardano-$network-.*\",container!=\"\"})\n",
     "legendFormat": "{{ container }} - {{ pod }}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod, container)(rate(container_cpu_usage_seconds_total{namespace=~\"dolos|ext-utxorpc-m1\", pod=~\"dolos-$network-az.*|cardano-$network-.*\", container!=\"\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dolos Disk Space Available",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes{persistentvolumeclaim=~\"pvc-.*|data-dolos-.*\", exported_namespace=~\"dolos|ext-utxorpc-m1\" } / on(persistentvolumeclaim) kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"pvc-.*|data-dolos-.*\", exported_namespace=~\"dolos|ext-utxorpc-m1\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate( utxorpc_proxy_total_requests{network=~\".*$network.*\"} [$__rate_interval])) by (status_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per customer",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate( utxorpc_proxy_total_requests{network=~\".*$network.*\"} [$__rate_interval])) by (consumer)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}