{
 "title": "Cardano Kupo Proxy",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "network", "query": "mainnet,preprod,preview" }
  ]
 },
 "panels": [
  { "title": "Proxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Request Rate by Consumer (blue)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by (consumer)(rate(kupo_proxy_http_total_request{namespace=\"ftr-kupo-v1\", exported_instance=~\".*$network.*\", job=~\"ftr-kupo-v1/proxy-blue-(cardano-)?$network\"}[5m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate by Code (blue)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(kupo_proxy_http_total_request{namespace=\"ftr-kupo-v1\", exported_instance=~\".*$network.*\", job=~\"ftr-kupo-v1/proxy-blue-(cardano-)?$network\" }[5m]) > 0) by (status_code)",
     "legendFormat": "{{status_code}}.{{consumer}}"
    }
   ]
  },
  {
   "title": "Request Rate by Consumer (green)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum by (consumer)(rate(kupo_proxy_http_total_request{namespace=\"ftr-kupo-v1\", exported_instance=~\".*$network.*\", job=~\"ftr-kupo-v1/proxy-green-(cardano-)?$network\"}[5m]) > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate by Code (green)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate(kupo_proxy_http_total_request{namespace=\"ftr-kupo-v1\", exported_instance=~\".*$network.*\", job=~\"ftr-kupo-v1/proxy-green-(cardano-)?$network\" }[5m]) > 0) by (status_code)",
     "legendFormat": "{{status_code}}.{{consumer}}"
    }
   ]
  }
 ]
}